name: Rock Box Photo
favicon: null
layout_spectrum: 0.49375189025886357
typography_spectrum: 0.18601544597186148
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.00043069571256637573
  lightness: 0.8589345905929804
  saturation: 0.2735908064059913
  rhythmicContrast: 0.5511764034163207
purpose: []
